// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

// Protobuf Java Version: 3.25.3
package com.bonfonte.proto.addressbook;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bonfonte.proto.addressbook.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .bonfonte.proto.addressbook.Person people = 1;</code>
   */
  java.util.List<com.bonfonte.proto.addressbook.Person> 
      getPeopleList();
  /**
   * <code>repeated .bonfonte.proto.addressbook.Person people = 1;</code>
   */
  com.bonfonte.proto.addressbook.Person getPeople(int index);
  /**
   * <code>repeated .bonfonte.proto.addressbook.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .bonfonte.proto.addressbook.Person people = 1;</code>
   */
  java.util.List<? extends com.bonfonte.proto.addressbook.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .bonfonte.proto.addressbook.Person people = 1;</code>
   */
  com.bonfonte.proto.addressbook.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
